apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-webui

resources:
  - namespace.yaml
  - ingress.yaml

helmCharts:
  - name: open-webui
    releaseName: openwebui
    version: 6.13.0
    repo: https://helm.openwebui.com/
    valuesFile: values.yaml
