# Istio ingress gateway configuration
# This creates a LoadBalancer service
service:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    name: http2
  - port: 443
    targetPort: 8443
    name: https

# Resources for gateway pods
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 2000m
    memory: 1024Mi

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# Pod anti-affinity for high availability
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app: istio-ingress
        topologyKey: kubernetes.io/hostname