apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow-user-example-com

# Resources for KV cache offloading with LMCache
resources:
  - redis-lmcache.yaml
  - lmcache-config.yaml
  - qwen3-2507-4b.yaml
  - aigateway.yaml

# Strategic merge patch for the inferenceservice-config ConfigMap
# namespace: kserve
# patchesStrategicMerge:
#   - modelcar-config-patch.yaml
