apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/envoyproxy/ai-gateway/main/manifests/envoy-gateway-config/redis.yaml
  - https://raw.githubusercontent.com/envoyproxy/ai-gateway/main/manifests/envoy-gateway-config/rbac.yaml
helmCharts:
  - name: gateway-helm
    repo: oci://docker.io/envoyproxy
    version: v0.0.0-latest
    releaseName: eg
    namespace: envoy-gateway-system
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - target:
      kind: ConfigMap
      name: envoy-gateway-config
    path: https://raw.githubusercontent.com/envoyproxy/ai-gateway/main/manifests/envoy-gateway-config/config.yaml
