apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
  - namespace.yml
  - instrumentation.yml
  - collector.yml


helmCharts:
- name: opentelemetry-operator
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  releaseName: opentelemetry-operator
  namespace: observability
  valuesFile: values.yml
  includeCRDs: true
