apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-platform-engineering

resources:
  - namespace.yaml
  # create secrets resource according to https://github.com/cnoe-io/ai-platform-engineering/tree/main/deploy/secrets-examples -
  - secrets.yaml

helmCharts:
  - name: ai-platform-engineering
    version: 0.2.32
    repo: oci://ghcr.io/cnoe-io/charts
    releaseName: ai-plae
    includeCRDs: true
    namespace: ai-platform-engineering
    valuesFile: values.yaml
